[package]
name = "vocana_sdk"
version = "0.0.1"
authors = ["CRIMX <straybugs@gmail.com>"]
description = "Vocana runner SDK in Rust"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
mainframe = { path = "../mainframe" }
clap = { version = "3.0.14", features = ["cargo", "derive"] }