name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build-compiler:
      name: Build and Test ${{ matrix.rust-host }}
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1

        - name: Build
          run: cargo build --release

        - name: Test
          run: cargo test