name: "Check PR Title Format"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-pr-format:
    permissions:
      pull-requests: read # for amannn/action-semantic-pull-request to analyze PRs
      statuses: write # for amannn/action-semantic-pull-request to mark status of analyzed PR
    name: Check PR Format
    runs-on: [ubuntu-latest]
    timeout-minutes: 3
    steps:
      - name: semantic-pull-request
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
          validateSingleCommit: false
          validateSingleCommitMatchesPrTitle: false
